/*
 * Copyright 2025 McXross
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package xyz.mcxross.kaptos.core.crypto

import xyz.mcxross.kaptos.core.AuthenticationKey
import xyz.mcxross.kaptos.model.*

/**
 * Implemented by optional authentication modules whose public keys are encoded inside Aptos'
 * `AnyPublicKey` enum. The payload returned by [toAnyPublicKeyBcs] excludes the enum variant.
 */
interface AnyPublicKeyCompatible {
  val anyPublicKeyVariant: AnyPublicKeyVariant

  fun toAnyPublicKeyBcs(): ByteArray
}

/**
 * Implemented by optional authentication modules whose signatures are encoded inside Aptos'
 * `AnySignature` enum. The payload returned by [toAnySignatureBcs] excludes the enum variant.
 */
interface AnySignatureCompatible {
  val anySignatureVariant: AnySignatureVariant

  fun toAnySignatureBcs(): ByteArray
}

/**
 * Implemented by optional public-key families that need a scheme-specific placeholder signature for
 * fullnode simulation.
 */
interface SimulationSignatureProvider {
  fun simulationSignature(): Signature
}

/**
 * Represents any public key supported by Aptos.
 *
 * Since [AIP-55](https://github.com/aptos-foundation/AIPs/pull/263) Aptos supports `Legacy` and
 * `Unified` authentication keys.
 *
 * Any unified authentication key is represented in the SDK as `AnyPublicKey`.
 */
class AnyPublicKey(val publicKey: PublicKey) : AccountPublicKey() {

  val variant: AnyPublicKeyVariant
    get() =
      when (publicKey) {
        is Ed25519PublicKey -> AnyPublicKeyVariant.Ed25519
        is Secp256k1PublicKey -> AnyPublicKeyVariant.Secp256k1
        is Secp256r1PublicKey -> AnyPublicKeyVariant.Secp256r1
        is AnyPublicKeyCompatible -> publicKey.anyPublicKeyVariant
        else -> throw IllegalArgumentException("Unsupported public key type")
      }

  override fun authKey(): AuthenticationKey {
    return AuthenticationKey.fromSchemeAndBytes(
      AuthenticationKeyScheme.Signing(SigningScheme.SingleKey),
      HexInput.fromByteArray(toBcs()),
    )
  }

  override fun verifySignature(message: HexInput, signature: Signature): Boolean {
    val actualSignature = if (signature is AnySignature) signature.signature else signature
    return publicKey.verifySignature(message, actualSignature)
  }

  override fun toByteArray(): ByteArray = toBcs()

  override fun toBcs(): ByteArray {
    val payload =
      if (publicKey is AnyPublicKeyCompatible) publicKey.toAnyPublicKeyBcs() else publicKey.toBcs()
    return encodeUleb128(variant.value) + payload
  }
}

/**
 * Instance of signature that uses the SingleKey authentication scheme. This signature can only be
 * generated by a `SingleKeySigner`, since it uses the same authentication scheme.
 */
class AnySignature(val signature: Signature) : Signature() {

  val variant: AnySignatureVariant =
    when (signature) {
      is Ed25519Signature -> AnySignatureVariant.Ed25519
      is Secp256k1Signature -> AnySignatureVariant.Secp256k1
      is WebAuthnSignature -> AnySignatureVariant.WebAuthn
      is AnySignatureCompatible -> signature.anySignatureVariant
      else -> throw IllegalArgumentException("Unsupported signature type")
    }

  override fun toByteArray(): ByteArray = toBcs()

  override fun toBcs(): ByteArray {
    val payload =
      if (signature is AnySignatureCompatible) signature.toAnySignatureBcs() else signature.toBcs()
    return encodeUleb128(variant.value) + payload
  }
}
