name: Docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true


jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Clear Gradle Cache
        run: rm -rf ~/.gradle/caches/
      - name: Cache Konan
        uses: ./.github/actions/cache-konan
      - name: Cache Gradle
        uses: ./.github/actions/cache-gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        shell: bash
      - name: Generate GraphQL Client
        run: ./gradlew graphqlGenerateClient --refresh-dependencies
        shell: bash
      - name: Generate HTML docs
        run: ./gradlew dokkaHtml --refresh-dependencies
        shell: bash
      - name: Deploy docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.9
        with:
          branch: gh-pages
          folder: lib/build/dokka
